-- Copyright (c) 2026, SoftlaneIT (https://softlaneit.com/) All Rights Reserved.
--
-- SoftlaneIT licenses this file to you under the Apache License,
-- Version 2.0 (the "LICENSE"); you may not use this file except
-- in compliance with the LICENSE.
-- You may obtain a copy of the LICENSE at
--
-- https://softlaneit.com/LICENSE.txt
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the LICENSE is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the LICENSE for the
-- specific language governing permissions and limitations
-- under the LICENSE.

-- 
-- 000006_create_webhooks.up
--
-- Two tables support the outbound webhook delivery system:
--
--   1. webhooks  — Endpoint registrations
--      Each tenant registers one or more HTTPS endpoints and declares which
--      event types they care about.  The platform signs each delivery with an
--      HMAC-SHA256 of the payload using the per-endpoint `secret`, so the
--      tenant can verify authenticity without TLS client certificates.
--
--   2. webhook_deliveries  — Immutable delivery log
--      Every delivery attempt is recorded here.  This enables:
--        • "Why didn't my webhook fire?" debugging in the management UI
--        • Automatic retry with exponential back-off (the dispatcher reads
--          rows with status='pending' or status='failed' and next_attempt_at
--          in the past)
--        • Replay: a developer can trigger a re-delivery of any past event
--          by resetting the status and clearing attempt counts
--
-- The dispatcher (Phase 2, event-bus consumer) is responsible for writing
-- delivery rows and updating their status.  The management UI reads them.
-- 

--  1. webhooks — endpoint registrations 
CREATE TABLE webhooks (
    id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id       UUID          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    -- HTTPS URL of the tenant's endpoint.  Validated by the platform on create.
    url             TEXT          NOT NULL,
    -- Event type filter.  Empty array = subscribe to all events from all
    -- subscribed modules.  Non-empty = only the listed types
    -- (e.g. '{"booking.created","payment.failed"}').
    events          TEXT[]        NOT NULL DEFAULT '{}',
    -- HMAC-SHA256 signing secret.  Generated by the platform on creation,
    -- shown once, stored hashed (SHA-256) here.
    -- TODO Phase 2: store only the hash; return the raw secret once on create.
    secret_hash     CHAR(64)      NOT NULL,
    -- Delivery retry policy stored as JSONB for flexibility.
    -- Default: 5 retries with exponential back-off, max delay 3600 s.
    retry_policy    JSONB         NOT NULL DEFAULT
                        '{"maxRetries": 5, "backoffType": "exponential", "initialDelaySeconds": 5, "maxDelaySeconds": 3600}',
    status          VARCHAR(20)   NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'paused', 'deleted')),
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_webhooks_updated_at
    BEFORE UPDATE ON webhooks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

--  Indices for webhooks 
-- Dispatcher fetches active endpoints for a tenant + event type.
CREATE INDEX idx_webhooks_tenant_status
    ON webhooks (tenant_id, status);

--  RLS for webhooks 
ALTER TABLE webhooks ENABLE ROW LEVEL SECURITY;

CREATE POLICY webhooks_tenant_isolation ON webhooks
    USING      (tenant_id = current_setting('app.current_tenant_id', TRUE)::UUID)
    WITH CHECK (tenant_id = current_setting('app.current_tenant_id', TRUE)::UUID);

--  2. webhook_deliveries — delivery attempt log 
CREATE TABLE webhook_deliveries (
    id                  UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
    webhook_id          UUID          NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
    tenant_id           UUID          NOT NULL REFERENCES tenants(id)  ON DELETE CASCADE,
    -- The event envelope JSON that was (or will be) delivered.
    event_type          VARCHAR(100)  NOT NULL,
    event_id            UUID          NOT NULL,  -- maps to events.Envelope traceId field
    payload             JSONB         NOT NULL,
    -- Delivery status state machine:
    --   pending → delivering → succeeded
    --                       → failed → pending (retry scheduled)
    --                                → dead_letter (max retries exhausted)
    status              VARCHAR(20)   NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'delivering', 'succeeded', 'failed', 'dead_letter')),
    -- HTTP response from the tenant's endpoint (NULL until first attempt).
    response_status     INTEGER,
    response_body       TEXT,
    -- Number of attempts made so far.
    attempt_count       INTEGER       NOT NULL DEFAULT 0,
    -- Timestamp for the next delivery attempt.  Set by the dispatcher after
    -- each failed attempt using the retry policy.  NULL = not yet scheduled.
    next_attempt_at     TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    -- Timestamp of the most recent attempt.
    last_attempted_at   TIMESTAMPTZ,
    -- Timestamp when delivery succeeded or was declared dead-letter.
    resolved_at         TIMESTAMPTZ
    -- No updated_at: individual columns are updated atomically by the dispatcher.
);

--  Indices for webhook_deliveries 
-- Dispatcher polling query: "give me pending/failed deliveries due for retry".
CREATE INDEX idx_webhook_deliveries_dispatch
    ON webhook_deliveries (status, next_attempt_at)
    WHERE status IN ('pending', 'failed');

-- Management UI: "show recent deliveries for this webhook, newest first".
CREATE INDEX idx_webhook_deliveries_webhook_created
    ON webhook_deliveries (webhook_id, created_at DESC);

-- Tenant-level delivery history.
CREATE INDEX idx_webhook_deliveries_tenant_created
    ON webhook_deliveries (tenant_id, created_at DESC);

-- Idempotency: prevent the dispatcher from double-inserting the same event
-- for the same endpoint.
CREATE UNIQUE INDEX uq_webhook_deliveries_event_endpoint
    ON webhook_deliveries (webhook_id, event_id);

--  RLS for webhook_deliveries ─
ALTER TABLE webhook_deliveries ENABLE ROW LEVEL SECURITY;

CREATE POLICY webhook_deliveries_tenant_isolation ON webhook_deliveries
    USING      (tenant_id = current_setting('app.current_tenant_id', TRUE)::UUID)
    WITH CHECK (tenant_id = current_setting('app.current_tenant_id', TRUE)::UUID);
