/*
 * Copyright (c) 2026, SoftlaneIT (https://softlaneit.com/) All Rights Reserved.
 *
 * SoftlaneIT licenses this file to you under the Apache License,
 * Version 2.0 (the "LICENSE"); you may not use this file except
 * in compliance with the LICENSE.
 * You may obtain a copy of the LICENSE at
 *
 * https://softlaneit.com/LICENSE.txt
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the LICENSE is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the LICENSE for the
 * specific language governing permissions and limitations
 * under the LICENSE.
 */

// Package domain defines the core Tenant aggregate and the business rules that
// govern it.  This package has zero external dependencies — all infrastructure
// concerns (persistence, HTTP) live in separate packages.
package domain

import (
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"
)

//  value types ─

// Plan represents the billing / feature tier assigned to a tenant.
type Plan string

const (
	PlanStarter    Plan = "starter"
	PlanPro        Plan = "pro"
	PlanEnterprise Plan = "enterprise"
)

// Valid reports whether p is a recognised plan value.
func (p Plan) Valid() bool {
	switch p {
	case PlanStarter, PlanPro, PlanEnterprise:
		return true
	}
	return false
}

// Status represents the lifecycle state of a tenant.
type Status string

const (
	StatusActive    Status = "active"
	StatusSuspended Status = "suspended"
	StatusDeleted   Status = "deleted"
)

// Valid reports whether s is a recognised status value.
func (s Status) Valid() bool {
	switch s {
	case StatusActive, StatusSuspended, StatusDeleted:
		return true
	}
	return false
}

//  aggregate ─

// Tenant is the root aggregate for the tenant-service.  Its ID is a UUID
// string generated by PostgreSQL (uuid_generate_v4()).
type Tenant struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Plan      Plan           `json:"plan"`
	Status    Status         `json:"status"`
	Settings  map[string]any `json:"settings,omitempty"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	// DeletedAt is nil for non-deleted tenants and omitted from JSON output.
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

//  command inputs

// CreateParams is the validated input for creating a new tenant.
// Call Validate() before passing to the repository.
type CreateParams struct {
	Name     string
	Slug     string
	Plan     Plan
	Settings map[string]any
}

// UpdateParams carries the optional fields for a partial tenant update (PATCH).
// A nil pointer means "leave the field unchanged".  Settings nil also means
// "leave unchanged"; to clear settings pass an empty map.
type UpdateParams struct {
	Name     *string
	Plan     *Plan
	Settings map[string]any
}

//  sentinel errors ─

// ErrNotFound is returned by the repository when a tenant does not exist or
// has been soft-deleted.
var ErrNotFound = errors.New("tenant not found")

// ErrSlugConflict is returned when an INSERT or UPDATE would violate the
// unique-slug constraint.
var ErrSlugConflict = errors.New("slug already taken")

//  validation

// slugRE accepts slugs that are 3-100 characters long, start and end with a
// lowercase alphanumeric character, and contain only lowercase alphanumeric
// characters or hyphens in between.
//
// Examples that pass: "acme", "acme-corp", "my-tenant-1"
// Examples that fail: "-acme", "acme-", "ACME", "ab" (too short), "a" (too short)
var slugRE = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{1,98}[a-z0-9]$`)

// Validate checks all fields of p for validity and returns a combined error
// message if any check fails.  It does NOT check uniqueness — that is the
// repository's responsibility.
func (p CreateParams) Validate() error {
	var errs []string

	name := strings.TrimSpace(p.Name)
	switch {
	case name == "":
		errs = append(errs, "name is required")
	case len(name) > 255:
		errs = append(errs, "name must be at most 255 characters")
	}

	slug := strings.TrimSpace(p.Slug)
	switch {
	case slug == "":
		errs = append(errs, "slug is required")
	case !slugRE.MatchString(slug):
		errs = append(errs,
			"slug must be 3-100 lowercase alphanumeric characters or hyphens, "+
				"and cannot start or end with a hyphen")
	}

	switch {
	case p.Plan == "":
		errs = append(errs, "plan is required")
	case !p.Plan.Valid():
		errs = append(errs,
			fmt.Sprintf("plan must be one of starter, pro, enterprise; got %q", p.Plan))
	}

	if len(errs) > 0 {
		return fmt.Errorf("validation: %s", strings.Join(errs, "; "))
	}
	return nil
}

// Validate checks the optional fields of p for validity.  At least one field
// must be set; all set fields must individually be valid.
func (p UpdateParams) Validate() error {
	var errs []string

	if p.Name == nil && p.Plan == nil && p.Settings == nil {
		errs = append(errs, "at least one field must be provided")
	}

	if p.Name != nil {
		name := strings.TrimSpace(*p.Name)
		switch {
		case name == "":
			errs = append(errs, "name must not be empty")
		case len(name) > 255:
			errs = append(errs, "name must be at most 255 characters")
		}
	}

	if p.Plan != nil && !p.Plan.Valid() {
		errs = append(errs,
			fmt.Sprintf("plan must be one of starter, pro, enterprise; got %q", *p.Plan))
	}

	if len(errs) > 0 {
		return fmt.Errorf("validation: %s", strings.Join(errs, "; "))
	}
	return nil
}
